export const countries = [
  { code: 'AF', name: 'Afganistán', postalPattern: /^\d{4}$/, postalExample: '1001' },
  { code: 'AL', name: 'Albania', postalPattern: /^\d{4}$/, postalExample: '1001' },
  { code: 'DE', name: 'Alemania', postalPattern: /^\d{5}$/, postalExample: '10115' },
  { code: 'AD', name: 'Andorra', postalPattern: /^AD\d{3}$/, postalExample: 'AD100' },
  { code: 'AO', name: 'Angola', postalPattern: /^.+$/, postalExample: '—' },
  { code: 'SA', name: 'Arabia Saudita', postalPattern: /^\d{5}(-\d{4})?$/, postalExample: '11564' },
  { code: 'DZ', name: 'Argelia', postalPattern: /^\d{5}$/, postalExample: '16000' },
  { code: 'AR', name: 'Argentina', postalPattern: /^[A-Z]\d{4}[A-Z]{3}$|^\d{4}$/, postalExample: 'C1234' },
  { code: 'AM', name: 'Armenia', postalPattern: /^\d{4}$/, postalExample: '0001' },
  { code: 'AU', name: 'Australia', postalPattern: /^\d{4}$/, postalExample: '2000' },
  { code: 'AT', name: 'Austria', postalPattern: /^\d{4}$/, postalExample: '1010' },
  { code: 'AZ', name: 'Azerbaiyán', postalPattern: /^AZ\d{4}$/, postalExample: 'AZ1000' },
  { code: 'BE', name: 'Bélgica', postalPattern: /^\d{4}$/, postalExample: '1000' },
  { code: 'BO', name: 'Bolivia', postalPattern: /^.+$/, postalExample: '—' },
  { code: 'BA', name: 'Bosnia y Herzegovina', postalPattern: /^\d{5}$/, postalExample: '71000' },
  { code: 'BR', name: 'Brasil', postalPattern: /^\d{5}-?\d{3}$/, postalExample: '01001-000' },
  { code: 'BG', name: 'Bulgaria', postalPattern: /^\d{4}$/, postalExample: '1000' },
  { code: 'CA', name: 'Canadá', postalPattern: /^[A-Z]\d[A-Z]\s?\d[A-Z]\d$/i, postalExample: 'K1A 0B1' },
  { code: 'CL', name: 'Chile', postalPattern: /^\d{7}$/, postalExample: '7500000' },
  { code: 'CN', name: 'China', postalPattern: /^\d{6}$/, postalExample: '100000' },
  { code: 'CO', name: 'Colombia', postalPattern: /^\d{6}$/, postalExample: '110111' },
  { code: 'KR', name: 'Corea del Sur', postalPattern: /^\d{5}$/, postalExample: '03000' },
  { code: 'CR', name: 'Costa Rica', postalPattern: /^\d{5}$/, postalExample: '10101' },
  { code: 'HR', name: 'Croacia', postalPattern: /^\d{5}$/, postalExample: '10000' },
  { code: 'CU', name: 'Cuba', postalPattern: /^\d{5}$/, postalExample: '10100' },
  { code: 'DK', name: 'Dinamarca', postalPattern: /^\d{4}$/, postalExample: '1000' },
  { code: 'EC', name: 'Ecuador', postalPattern: /^\d{6}$/, postalExample: '170150' },
  { code: 'EG', name: 'Egipto', postalPattern: /^\d{5}$/, postalExample: '11511' },
  { code: 'SV', name: 'El Salvador', postalPattern: /^\d{4}$/, postalExample: '1101' },
  { code: 'AE', name: 'Emiratos Árabes Unidos', postalPattern: /^.+$/, postalExample: '—' },
  { code: 'SK', name: 'Eslovaquia', postalPattern: /^\d{3}\s?\d{2}$/, postalExample: '811 01' },
  { code: 'SI', name: 'Eslovenia', postalPattern: /^\d{4}$/, postalExample: '1000' },
  { code: 'ES', name: 'España', postalPattern: /^\d{5}$/, postalExample: '28001' },
  { code: 'US', name: 'Estados Unidos', postalPattern: /^\d{5}(-\d{4})?$/, postalExample: '10001' },
  { code: 'EE', name: 'Estonia', postalPattern: /^\d{5}$/, postalExample: '10111' },
  { code: 'PH', name: 'Filipinas', postalPattern: /^\d{4}$/, postalExample: '1000' },
  { code: 'FI', name: 'Finlandia', postalPattern: /^\d{5}$/, postalExample: '00100' },
  { code: 'FR', name: 'Francia', postalPattern: /^\d{5}$/, postalExample: '75001' },
  { code: 'GE', name: 'Georgia', postalPattern: /^\d{4}$/, postalExample: '0100' },
  { code: 'GH', name: 'Ghana', postalPattern: /^.+$/, postalExample: '—' },
  { code: 'GR', name: 'Grecia', postalPattern: /^\d{3}\s?\d{2}$/, postalExample: '104 31' },
  { code: 'GT', name: 'Guatemala', postalPattern: /^\d{5}$/, postalExample: '01001' },
  { code: 'HN', name: 'Honduras', postalPattern: /^\d{5}$/, postalExample: '11101' },
  { code: 'HK', name: 'Hong Kong', postalPattern: /^.+$/, postalExample: '—' },
  { code: 'HU', name: 'Hungría', postalPattern: /^\d{4}$/, postalExample: '1011' },
  { code: 'IN', name: 'India', postalPattern: /^\d{6}$/, postalExample: '110001' },
  { code: 'ID', name: 'Indonesia', postalPattern: /^\d{5}$/, postalExample: '10110' },
  { code: 'IE', name: 'Irlanda', postalPattern: /^[A-Z\d]{3}\s?[A-Z\d]{4}$/i, postalExample: 'D01 F5P2' },
  { code: 'IS', name: 'Islandia', postalPattern: /^\d{3}$/, postalExample: '101' },
  { code: 'IL', name: 'Israel', postalPattern: /^\d{7}$/, postalExample: '6100000' },
  { code: 'IT', name: 'Italia', postalPattern: /^\d{5}$/, postalExample: '00100' },
  { code: 'JM', name: 'Jamaica', postalPattern: /^.+$/, postalExample: '—' },
  { code: 'JP', name: 'Japón', postalPattern: /^\d{3}-?\d{4}$/, postalExample: '100-0001' },
  { code: 'KE', name: 'Kenia', postalPattern: /^\d{5}$/, postalExample: '00100' },
  { code: 'LV', name: 'Letonia', postalPattern: /^LV-\d{4}$/, postalExample: 'LV-1001' },
  { code: 'LT', name: 'Lituania', postalPattern: /^LT-\d{5}$/, postalExample: 'LT-01001' },
  { code: 'LU', name: 'Luxemburgo', postalPattern: /^\d{4}$/, postalExample: '1009' },
  { code: 'MY', name: 'Malasia', postalPattern: /^\d{5}$/, postalExample: '50000' },
  { code: 'MA', name: 'Marruecos', postalPattern: /^\d{5}$/, postalExample: '10000' },
  { code: 'MX', name: 'México', postalPattern: /^\d{5}$/, postalExample: '06600' },
  { code: 'NG', name: 'Nigeria', postalPattern: /^\d{6}$/, postalExample: '100001' },
  { code: 'NO', name: 'Noruega', postalPattern: /^\d{4}$/, postalExample: '0001' },
  { code: 'NZ', name: 'Nueva Zelanda', postalPattern: /^\d{4}$/, postalExample: '6011' },
  { code: 'NL', name: 'Países Bajos', postalPattern: /^\d{4}\s?[A-Z]{2}$/i, postalExample: '1011 AB' },
  { code: 'PA', name: 'Panamá', postalPattern: /^\d{4}$/, postalExample: '0801' },
  { code: 'PY', name: 'Paraguay', postalPattern: /^\d{4}$/, postalExample: '1209' },
  { code: 'PE', name: 'Perú', postalPattern: /^\d{5}$/, postalExample: '15001' },
  { code: 'PL', name: 'Polonia', postalPattern: /^\d{2}-\d{3}$/, postalExample: '00-001' },
  { code: 'PT', name: 'Portugal', postalPattern: /^\d{4}-\d{3}$/, postalExample: '1000-001' },
  { code: 'GB', name: 'Reino Unido', postalPattern: /^[A-Z]{1,2}\d[A-Z\d]?\s?\d[A-Z]{2}$/i, postalExample: 'SW1A 1AA' },
  { code: 'CZ', name: 'República Checa', postalPattern: /^\d{3}\s?\d{2}$/, postalExample: '110 00' },
  { code: 'DO', name: 'República Dominicana', postalPattern: /^\d{5}$/, postalExample: '10101' },
  { code: 'RO', name: 'Rumania', postalPattern: /^\d{6}$/, postalExample: '010011' },
  { code: 'RU', name: 'Rusia', postalPattern: /^\d{6}$/, postalExample: '101000' },
  { code: 'SG', name: 'Singapur', postalPattern: /^\d{6}$/, postalExample: '018956' },
  { code: 'ZA', name: 'Sudáfrica', postalPattern: /^\d{4}$/, postalExample: '2000' },
  { code: 'SE', name: 'Suecia', postalPattern: /^\d{3}\s?\d{2}$/, postalExample: '111 22' },
  { code: 'CH', name: 'Suiza', postalPattern: /^\d{4}$/, postalExample: '3000' },
  { code: 'TH', name: 'Tailandia', postalPattern: /^\d{5}$/, postalExample: '10100' },
  { code: 'TW', name: 'Taiwán', postalPattern: /^\d{3,5}$/, postalExample: '100' },
  { code: 'TR', name: 'Turquía', postalPattern: /^\d{5}$/, postalExample: '06100' },
  { code: 'UA', name: 'Ucrania', postalPattern: /^\d{5}$/, postalExample: '01001' },
  { code: 'UY', name: 'Uruguay', postalPattern: /^\d{5}$/, postalExample: '11000' },
  { code: 'VE', name: 'Venezuela', postalPattern: /^\d{4}(-[A-Z])?\d*$/, postalExample: '1010' },
  { code: 'VN', name: 'Vietnam', postalPattern: /^\d{6}$/, postalExample: '100000' },
];
